name: Build binary

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build with Cargo
        run: cargo build --release

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: imv-rs-linux-x86_64
          path: target/release/imv-rs
