name: Build and Release imv-rs

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build imv-rs binary
        run: cargo build --release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: imv-rs_linux_x86_64
          path: target/release/imv-rs

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: imv-rs_linux_x86_64
          path: build/

      - name: Create or update "latest" release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest release
          files: build/imv-rs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
